M48
; DRILL file {KiCad 9.0.6} date 2026-01-12T10:20:29-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-12T10:20:29-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.711
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.889
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X117.347Y-129.0
T2
X101.955Y-129.0
T3
X147.3Y-78.8
X147.3Y-97.45
X147.3Y-104.2
X147.3Y-112.92
M30
